- name: Install virtualenv package
  apt:
    name: python3-virtualenv
    state: present
    
- name: Create deployment directory
  file:
    path: "{{ app_dir }}"
    state: directory
    
- name: Create virtual environment
  pip:
    name:
      - flask
      - wheel
    virtualenv: "{{ app_dir }}/venv"
    
- name: Copy wheel file
  copy:
    src: /home/ubuntu/ansible-project-netsquare/files
    dest: "{{ app_dir }}"   

- name: Deploy Flask application
  pip:
    name: "/opt/example/{{ app_wheel }}"
    virtualenv: "{{ app_dir }}/venv"

- name: Copy app.py
  template:
    src: app.py
    dest: "{{ app_dir }}/app.py"

- name: Start Flask application
  command: "{{ app_dir }}/venv/bin/flask run -p {{ app_port }}"
